export const permissions = {
    CACHECLEAR: "cache:clear",
    USERCREATE: "user:create",
    USERREAD: "user:read",
    USERUPDATE: "user:update",
    USERDELETE: "user:delete", 
    BRANDCREATE: "brand:create",
    BRANDREAD: "brand:read",
    BRANDUPDATE: "brand:update",
    BRANDDELETE: "brand:delete",
    CATEGORYCREATE: "category:create",
    CATEGORYREAD: "category:read",
    CATEGORYUPDATE: "category:update",
    CATEGORYDELETE: "category:delete",
    PRODUCTCREATE: "product:create",
    PRODUCTREAD: "product:read",
    PRODUCTUPDATE: "product:update",
    PRODUCTDELETE: "product:delete",
    EXHIBITIONCREATE: "exhibition:create",
    EXHIBITIONREAD: "exhibition:read",
    EXHIBITIONUPDATE: "exhibition:update",
    EXHIBITIONDELETE: "exhibition:delete",

} as const;
